# Generated by Django 5.2.5 on 2025-08-24 12:03

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(default=None, null=True, upload_to=student.models.student_directory_name)),
                ('password', models.CharField(max_length=100)),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
